platform :ios, '5.0'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'JSONKit'
pod 'MKHorizMenu'
pod 'SDURLCache', '1.2'
pod 'MBProgressHUD'
pod 'InAppSettingsKit'
pod 'SVWebViewController'
pod 'MFSideMenu', '0.2'
pod 'TestFlightSDK'
pod 'TapkuLibrary'
pod 'ABCalendarPicker', '~> 1.0.2'
