platform :ios, '5.0'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'SDURLCache', '~> 1.2'
pod 'MKHorizMenu'
pod 'MBProgressHUD'
pod 'InAppSettingsKit'
pod 'SVWebViewController'
pod 'MFSideMenu', '0.2'
pod 'TestFlightSDK'
pod 'ABCalendarPicker', '~> 1.0.2'
pod 'CKCalendar'
pod 'ISRefreshControl', '~> 1.0.2'
pod 'MTLocation', '~> 0.9'
